codecov:
  token: 33935385-9c7e-4b74-b82e-7d55c7e00ca0

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
